# Generated by Django 2.0.4 on 2018-04-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=120)),
                ('news_likes', models.IntegerField()),
                ('news_text', models.TextField()),
                ('news_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
